// Saga
export const AUTHORIZE_SESSION = "AUTHORIZE_SESSION";
export const LIST_REPOSITORIES = "LIST_REPOSITORIES";
export const LIST_ORGANIZATIONS = "LIST_ORGANIZATIONS";
export const SEARCH_USER = "SEARCH_USER";

// Reducer
export const AUTHORIZE_SESSION_SUCCESS = "AUTHORIZE_SESSION_SUCCESS";
export const FETCH_REPOSITORIES_SUCCESS = "FETCH_REPOSITORIES_SUCCESS";
export const FETCH_ORGANIZATIONS_SUCCESS = "FETCH_ORGANIZATIONS_SUCCESS";
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS";

export const AUTHORIZE_SESSION_REJECT = "AUTHORIZE_SESSION_REJECT";
export const FETCH_REPOSITORIES_REJECT = "FETCH_REPOSITORIES_REJECT";
export const FETCH_ORGANIZATIONS_REJECT = "FETCH_ORGANIZATIONS_REJECT";
export const SEARCH_USER_REJECT = "SEARCH_USER_REJECT";

export const AUTHORIZE_SESSION_PENDING = "AUTHORIZE_SESSION_PENDING";
export const FETCH_REPOSITORIES_PENDING = "FETCH_REPOSITORIES_PENDING";
export const FETCH_ORGANIZATIONS_PENDING = "FETCH_ORGANIZATIONS_PENDING";
export const SEARCH_USER_PENDING = "SEARCH_USER_PENDING";
